name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.Yaseen@10 }}" | docker login -u ${{ secrets.yaseen778 }} --password-stdin

    - name: Build and push backend image
      run: |
        docker build -t yaseen778/dd-backend ./backend
        docker tag yaseen778/dd-backend yaseen778/dd-backend:latest
        docker push yaseen778/dd-backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t yaseen778/dd-frontend ./frontend
        docker tag yaseen778/dd-frontend yaseen778/dd-frontend:latest
        docker push yaseen778/dd-frontend:latest

    - name: Deploy on EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd ~/discover-dollar-mean-devops-task &&
          git pull &&
          docker-compose pull &&
          docker-compose up -d
        "
